name: walletonbankingapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.3

  intl: ^0.16.1
  intl_translation: ^0.17.10

  # state management
  stacked: ^1.7.6
  stacked_hooks: ^0.1.3
  flutter_hooks: ^0.12.0
  # navigation
  auto_route:
  stacked_services: ^0.5.2
  # inversion of control
  get_it:
  injectable:

  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  morpheus: ^1.2.2+1
  connectivity: ^0.4.9
  toast: ^0.1.5
  path_provider: ^1.6.11
  retry: ^3.0.1
  overlay_support: ^1.0.5
  esys_flutter_share: ^1.0.2
  shared_preferences: ^0.5.8
  package_info: ^0.4.1
  url_launcher: ^5.5.0
  permission_handler: ^5.0.1+1
  flutter_svg: ^0.18.0
  google_fonts: ^1.1.0
  cached_network_image: ^2.2.0+1
  json_annotation: ^3.0.1
  flutter_secure_storage: ^3.3.3
  image_picker: ^0.6.7+4
  flutter_native_image: ^0.0.5+2
  flutter_exif_rotation: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator:
  injectable_generator:

flutter:
  uses-material-design: true
